# 1 - Imports

In [1]:
import sys
from pathlib import Path

sys.path.append(str(Path().resolve().parents[0]))

In [2]:
from src.utils import config, io

/Users/hippolytegrandet/Desktop/Dev/country_risk_rating/.venv/lib/python3.9/site-packages/pypdf/_crypt_providers/_cryptography.py:32: CryptographyDeprecationWarning: ARC4 has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.ARC4 and will be removed from cryptography.hazmat.primitives.ciphers.algorithms in 48.0.0.
  from cryptography.hazmat.primitives.ciphers.algorithms import AES, ARC4

# 2 - Data Extraction

## 2.1 - OECD Rating

In [16]:
from src.extraction import build_oecd_dataset

### 2.1.1 - Yearly Rating Dataset

In [ ]:
oecd_rating_matrix_y = build_oecd_dataset.get_clean_oecd_rating_df(oecd_fname='02-02-2024', date_freq='Y')
oecd_rating_matrix_y

Reading CSV

,1999-01-01,2000-01-01,2001-01-01,2002-01-01,2003-01-01,2004-01-01,2005-01-01,2006-01-01,2007-01-01,2008-01-01,...,2014-01-01,2015-01-01,2016-01-01,2017-01-01,2018-01-01,2019-01-01,2020-01-01,2021-01-01,2022-01-01,2023-01-01
ISO3_COUNTRY_CODE,,,,,,,,,,,,,,,,,,,,,
AFG,7,7,-,-,-,-,-,-,-,7,...,7,7,7,7,7,7,7,7,7,7
ALB,7,7,7,7,7,7,6,6,6,6,...,6,6,6,6,6,6,5,5,5,5
DZA,6,6,5,5,4,4,4,3,3,3,...,3,3,3,4,4,4,4,5,5,5
AND,-,-,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
AGO,7,7,7,7,7,7,7,7,7,7,...,5,5,5,6,6,6,6,6,6,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
VNM,6,6,6,6,5,5,5,5,5,4,...,5,5,5,5,5,5,4,4,4,4
PSE,-,-,-,-,-,-,-,-,-,-,...,7,7,7,7,7,7,7,7,7,7
YEM,7,7,7,6,6,6,6,6,6,6,...,7,7,7,7,7,7,7,7,7,7
ZMB,7,7,7,7,7,7,7,7,7,6,...,5,5,5,6,6,6,7,7,7,7
ZWE,5,6,7,7,7,7,7,7,7,7,...,7,7,7,7,7,7,7,7,7,7

In [ ]:
io.save_csv(oecd_rating_matrix_y, config.INTERIM_DATA_DIR / 'oecd_rating_matrix_yearly.csv', index=True)

### 2.1.2 - Quarterly Rating Dataset

In [89]:
oecd_rating_matrix_q = build_oecd_dataset.get_clean_oecd_rating_df(oecd_fname='02-02-2024', date_freq='Q')
oecd_rating_matrix_q

Reading CSV

,1999-01-01,1999-04-01,1999-07-01,1999-10-01,2000-01-01,2000-04-01,2000-07-01,2000-10-01,2001-01-01,2001-04-01,...,2021-07-01,2021-10-01,2022-01-01,2022-04-01,2022-07-01,2022-10-01,2023-01-01,2023-04-01,2023-07-01,2023-10-01
ISO3_COUNTRY_CODE,,,,,,,,,,,,,,,,,,,,,
AFG,7,7,7,7,7,-,-,-,-,-,...,7,7,7,7,7,7,7,7,7,7
ALB,7,7,7,7,7,7,7,7,7,7,...,5,5,5,5,5,5,5,5,5,5
DZA,6,6,6,6,6,6,6,5,5,5,...,5,5,5,5,5,5,5,5,5,5
AND,-,-,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
AGO,7,7,7,7,7,7,7,7,7,7,...,6,6,6,6,6,6,6,6,6,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
VNM,6,6,6,6,6,6,6,6,6,6,...,4,4,4,4,4,4,4,4,4,4
PSE,-,-,-,-,-,-,-,-,-,-,...,7,7,7,7,7,7,7,7,7,7
YEM,7,7,7,7,7,7,7,7,7,7,...,7,7,7,7,7,7,7,7,7,7
ZMB,7,7,7,7,7,7,7,7,7,7,...,7,7,7,7,7,7,7,7,7,7
ZWE,5,6,6,6,6,7,7,7,7,7,...,7,7,7,7,7,7,7,7,7,7

In [90]:
io.save_csv(oecd_rating_matrix_q, config.INTERIM_DATA_DIR / 'oecd_rating_matrix_quarterly.csv', index=True)

## 2.2 - World Bank Features

In [10]:
from src.extraction import world_bank, world_bank_WDI_indicators

In [11]:
oecd_rating_matrix = io.load_csv(config.INTERIM_DATA_DIR / 'oecd_rating_matrix_yearly.csv', index_col=0)
oecd_countries = list(oecd_rating_matrix.index)
min_year = int(min(oecd_rating_matrix.columns)[:4])
max_year = int(max(oecd_rating_matrix.columns)[:4])

In [12]:
wb_df = world_bank.get_world_bank_indicators(
    indicators=world_bank_WDI_indicators.WORLD_BANK_INDICATORS,
    countries=oecd_countries,
    start_year=min_year,
    end_year=max_year,
)
wb_df

GDP (current US$) NY.GDP.MKTP.CD
GDP growth (annual %) NY.GDP.MKTP.KD.ZG
GDP, PPP (current international $) NY.GDP.MKTP.PP.CD
GDP per capita (current US$) NY.GDP.PCAP.CD
GDP per capita growth (annual %) NY.GDP.PCAP.KD.ZG
Gross capital formation (annual % growth) NE.GDI.TOTL.KD.ZG
Gross capital formation (% of GDP) NE.GDI.TOTL.ZS
Industry (including construction), value added (current US$) NV.IND.TOTL.CD
Industry (including construction), value added (annual % growth) NV.IND.TOTL.KD.ZG
Industry (including construction), value added (% of GDP) NV.IND.TOTL.ZS
Employment in industry (% of total employment) (modeled ILO estimate) SL.IND.EMPL.ZS
Services, value added (current US$) NV.SRV.TOTL.CD
Services, value added (annual % growth) NV.SRV.TOTL.KD.ZG
Services, value added (% of GDP) NV.SRV.TOTL.ZS
GNI growth (annual %) NY.GNP.MKTP.KD.ZG
GNI, PPP (current international $) NY.GNP.MKTP.PP.CD
Trade in services (% of GDP) BG.GSR.NFSV.GD.ZS
Market capitalization of listed domestic companies (% of GDP) CM.MKT.LCAP.GD.ZS
Stocks traded, total value (% of GDP) CM.MKT.TRAD.GD.ZS
Gross domestic savings (% of GDP) NY.GDS.TOTL.ZS
Gross savings (% of GDP) NY.GNS.ICTR.ZS
Trade (% of GDP) NE.TRD.GNFS.ZS
Central government debt, total (% of GDP) GC.DOD.TOTL.GD.ZS
Use of IMF credit (DOD, current US$) DT.DOD.DIMF.CD
Revenue, excluding grants (% of GDP) GC.REV.XGRT.GD.ZS
Expense (% of GDP) GC.XPN.TOTL.GD.ZS
Inflation, consumer prices (annual %) FP.CPI.TOTL.ZG
Inflation, GDP deflator (annual %) NY.GDP.DEFL.KD.ZG
Real interest rate (%) FR.INR.RINR
Broad money (% of GDP) FM.LBL.BMNY.GD.ZS
Broad money growth (annual %) FM.LBL.BMNY.ZG
Current account balance (current US$) BN.CAB.XOKA.CD
Imports of goods and services (% of GDP) NE.IMP.GNFS.ZS
Exports of goods and services (% of GDP) NE.EXP.GNFS.ZS
Current account balance (% of GDP) BN.CAB.XOKA.GD.ZS
Taxes on international trade (% of revenue) GC.TAX.INTT.RV.ZS
Foreign direct investment, net outflows (% of GDP) BM.KLT.DINV.WD.GD.ZS
Foreign direct investment, net inflows (% of GDP) BX.KLT.DINV.WD.GD.ZS
Present value of external debt (% of GNI) DT.DOD.PVLX.GN.ZS
External debt stocks (% of GNI) DT.DOD.DECT.GN.ZS
External debt stocks, long-term (DOD, current US$) DT.DOD.DLXF.CD
External debt stocks, short-term (DOD, current US$) DT.DOD.DSTC.CD
Debt service on external debt, total (TDS, current US$) DT.TDS.DECT.CD
External balance on goods and services (% of GDP) NE.RSB.GNFS.ZS
Total reserves in months of imports FI.RES.TOTL.MO
Exports of goods and services (current US$) NE.EXP.GNFS.CD
Imports of goods and services (current US$) NE.IMP.GNFS.CD
High-technology exports (current US$) TX.VAL.TECH.CD
Total debt service (% of GNI) DT.TDS.DECT.GN.ZS
Short-term debt (% of total reserves) DT.DOD.DSTC.IR.ZS
Interest payments (% of revenue) GC.XPN.INTP.RV.ZS
Interest payments (% of expense) GC.XPN.INTP.ZS
Deposit interest rate (%) FR.INR.DPST
Lending interest rate (%) FR.INR.LEND
General government final consumption expenditure (% of GDP) NE.CON.GOVT.ZS
Households and NPISHs final consumption expenditure (% of GDP) NE.CON.PRVT.ZS
Final consumption expenditure (% of GDP) NE.CON.TOTL.ZS
Gross national expenditure (% of GDP) NE.DAB.TOTL.ZS
Bank assets to GDP (%) FS.AST.DOMO.GD.ZS
Unemployment, youth total (% of total labor force ages 15-24) (modeled ILO estimate) SL.UEM.1524.ZS
Unemployment with intermediate education (% of total labor force with intermediate education) SL.UEM.INTM.ZS
Unemployment with basic education (% of total labor force with basic education) SL.UEM.BASC.ZS
Unemployment, total (% of total labor force) (modeled ILO estimate) SL.UEM.TOTL.ZS
Population in the largest city (% of urban population) EN.URB.LCTY.UR.ZS
Population, total SP.POP.TOTL
Population growth (annual %) SP.POP.GROW
Urban population (% of total population) SP.URB.TOTL.IN.ZS
Population density (people per sq. km of land area) EN.POP.DNST
Educational attainment, at least completed primary, population 25+ years, total (%) (cumulative) SE.PRM.CUAT.ZS
Age dependency ratio (% of working-age population) SP.POP.DPND
Labor force participation rate, total (% of total population ages 15+) (modeled ILO estimate) SL.TLF.CACT.ZS
Government Effectiveness: Estimate GE.EST
Regulatory Quality: Estimate RQ.EST
B-READY: Business Insolvency: Overall Score IC.BRE.BI.OS
B-READY: Business Entry: Overall Score IC.BRE.BE.OS
CPIA quality of public administration rating (1=low to 6=high) IQ.CPA.PADM.XQ
Domestic credit to private sector (% of GDP) FS.AST.PRVT.GD.ZS
Monetary Sector credit to private sector (% GDP) FM.AST.PRVT.GD.ZS

,NY.GDP.MKTP.CD,NY.GDP.MKTP.KD.ZG,NY.GDP.MKTP.PP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.KD.ZG,NE.GDI.TOTL.KD.ZG,NE.GDI.TOTL.ZS,NV.IND.TOTL.CD,NV.IND.TOTL.KD.ZG,NV.IND.TOTL.ZS,...,SE.PRM.CUAT.ZS,SP.POP.DPND,SL.TLF.CACT.ZS,GE.EST,RQ.EST,IC.BRE.BI.OS,IC.BRE.BE.OS,IQ.CPA.PADM.XQ,FS.AST.PRVT.GD.ZS,FM.AST.PRVT.GD.ZS
COUNTRY_PERIOD_INDEX,,,,,,,,,,,,,,,,,,,,,
ABW-1999,1.722905e+09,1.238042,2.489441e+09,19216.197235,-0.125966,NaN,30.869001,2.678827e+08,NaN,15.548314,...,NaN,43.669781,NaN,NaN,NaN,NaN,NaN,NaN,44.620525,44.620525
AFG-1999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,108.686031,46.609,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AGO-1999,6.152923e+09,2.181490,5.669622e+10,392.725539,-1.130799,NaN,NaN,NaN,NaN,NaN,...,NaN,93.586677,77.380,NaN,NaN,NaN,NaN,NaN,NaN,2.573386
ALB-1999,3.283942e+09,12.250728,1.112055e+10,1056.344812,12.963927,31.190830,24.271511,6.082915e+08,20.139252,18.523214,...,NaN,59.064263,62.061,NaN,NaN,NaN,NaN,NaN,NaN,4.116988
AND-1999,1.240295e+09,4.099079,2.075776e+09,18875.288370,3.579455,NaN,NaN,NaN,NaN,NaN,...,NaN,37.399632,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
WSM-2023,1.044910e+09,15.233611,1.775512e+09,4822.740847,14.487948,27.487930,36.068083,1.053197e+08,-1.836608,10.079316,...,NaN,79.964616,43.438,0.492577,-0.270535,NaN,NaN,4.0,74.148912,39.843664
YEM-2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,45.513580,77.726093,33.106,-2.275420,-1.843051,NaN,NaN,1.5,NaN,NaN
ZAF-2023,3.814407e+11,0.806105,9.608114e+11,6034.272090,-0.523851,-1.777435,15.391317,9.369697e+10,-0.324993,24.563966,...,87.625877,48.367934,55.020,-0.256947,-0.223698,NaN,NaN,NaN,90.372482,57.519623
ZMB-2023,2.757796e+10,5.367943,8.449150e+10,1330.727806,2.464640,NaN,31.445069,9.682008e+09,0.871063,35.107778,...,NaN,78.106992,61.961,-0.658970,-0.498100,NaN,NaN,3.0,NaN,12.813158
ZWE-2023,3.587178e+10,5.350869,9.463284e+10,2195.224921,3.598767,18.313137,10.023043,1.192936e+10,3.242902,33.255552,...,NaN,81.625352,67.786,-1.170335,-1.338359,NaN,NaN,3.0,6.477697,6.477697

In [13]:
io.save_csv(wb_df, config.INTERIM_DATA_DIR / 'worldbank_dataset_extracted.csv', index=True)